"""user authentification migration

Revision ID: 117b6ec19ba8
Revises: cf0b017a1c58
Create Date: 2017-10-23 12:25:03.482540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117b6ec19ba8'
down_revision = 'cf0b017a1c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
